'use strict';
// Deliberately small, edited library. Dates change only after substantive review.
const reviewed = '2026-10-07';
const sources = {
  appleSync: ['Apple: how iCloud Photos handles originals and deletions', 'https://support.apple.com/en-us/108782'],
  appleCopy: ['Apple: archive or make copies of iCloud information', 'https://support.apple.com/en-us/108306'],
  googleBackup: ['Google Photos: backup status and device folders', 'https://support.google.com/photos/answer/6193313?hl=en&co=GENIE.Platform%3DAndroid'],
  googleDelete: ['Google Photos: deleting photos and videos', 'https://support.google.com/photos/answer/6128858?hl=en'],
  googleFree: ['Google Photos: free up space on an Android device', 'https://support.google.com/photos/answer/6128843?hl=en'],
  googleQuality: ['Google Photos: backup quality and compression', 'https://support.google.com/photos/answer/6220791?hl=en'],
  digest: ['MDN: the browser digest API and its memory limitation', 'https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest']
};
const guides = [
{
 slug: 'before-deleting-photos', category: '01 / Understand the risk', title: 'Before deleting photos: separate sync from an independent copy',
 description: 'Map where your originals live, distinguish cloud deletion from device cleanup, and find the missing evidence before removing a photo library.',
 minutes: 7, sources: ['appleSync','googleDelete','googleFree','googleBackup'],
 sections: [
 ['start', 'The question is not “Can I see the photo?”', `<p>A thumbnail is a useful starting point, not a recovery plan. The practical question is: <strong>if this phone disappeared, could I obtain a usable copy without it?</strong> A second question matters just as much: would that copy survive an accidental deletion in the app I use every day?</p><p>This guide uses a copy map to answer those questions. It is for personal photo libraries, not forensic recovery or business retention. Stop before deletion if the only available copy is on a failing device; repeated attempts to organize or rewrite it can make a recovery situation harder.</p><p>Start by choosing one small, non-sensitive sample: an older photo, a recent photo and a video. Do not delete those samples as a test. Their job is to reveal gaps before you change your library.</p>`],
 ['map', 'Draw the copy map before choosing a cleanup button', `<div class="copy-map" role="img" aria-label="Phone and cloud library are linked by sync. A separately exported copy is a different branch, provided it is outside that sync."><div><strong>Phone</strong><span>Daily photo library</span></div><span class="map-arrow">↔<small>Sync</small></span><div><strong>Cloud library</strong><span>Account-dependent</span></div><span class="map-arrow">→<small>Export</small></span><div><strong>Separate copy</strong><span>Outside that sync</span></div></div><p>Label locations, not devices. Two folders on one laptop share that laptop’s failure risk. Two devices signed into the same synchronized library can share deletion behavior. A drive containing a deliberate export is a separate branch only if your synchronization or backup rules do not remove it when the working library changes.</p><p>Write down a simple test for each arrow: “Will a deletion here change the destination?” If you cannot answer from the service documentation and your settings, label the destination <em>unknown</em>. Do not count it as an independent copy yet.</p>`],
 ['actions', 'Three actions that sound similar but do different things', `<div class="table-wrap"><table><caption>Service behavior checked October 7, 2026. Check the actual confirmation screen before acting.</caption><thead><tr><th>Action</th><th>What the provider describes</th><th>What to verify first</th></tr></thead><tbody><tr><th>Delete in iCloud Photos</th><td>Deletion is reflected across devices using iCloud Photos.</td><td>An independent export, not just another synchronized device.</td></tr><tr><th>Delete in Google Photos</th><td>The app’s delete action can remove the device copy and backed-up copies across devices with backup enabled.</td><td>Whether you intend to remove the cloud item, not merely free phone space.</td></tr><tr><th>Google Photos “Free up space” on Android</th><td>Removes backed-up device copies. Cloud access remains, but those removed local files are not available offline in the device gallery.</td><td>Completed backup, correct account, and which files you still need offline.</td></tr></tbody></table></div><p>These are different operations, not interchangeable instructions. Apple’s Optimize Storage keeps smaller device versions as needed while originals remain in iCloud. That helps device capacity but is not a separate archive. The official links below explain the service details; menus vary by app and OS version.</p>`],
 ['example', 'Worked example: a reassuring count that hides a gap', `<p><strong>Hypothetical case:</strong> a family sees 8,400 items on the phone and 8,400 in the cloud. The matching total does not establish that all 8,400 are the same items, that videos play, or that an export contains the wanted originals. One omitted video and one duplicate image could leave the count unchanged.</p><ol><li>Check a recent photo that should have uploaded after the last trip.</li><li>Check an old photo from a folder that was imported rather than captured by this phone.</li><li>Export a video, then play its beginning, middle and end from the export.</li><li>Record where the exported samples were opened and whether that location participates in sync.</li></ol><p>If the imported folder is absent, the appropriate next task is to identify the missing scope—not to delete until counts happen to match. Google Photos exposes backup status and folder settings; those are useful checks, but the sample still needs to match the library you intend to preserve.</p>`],
 ['next', 'Leave with evidence, not a green badge', `<p>For each important group, record a location, the format you need, the export date and a successful opening check. Do not put account identifiers or private filenames into public support reports. A sample is deliberately limited: it can expose a problem, but cannot prove every item is recoverable.</p><p>Use the <a href="/tools/photo-backup-check/">photo backup self-check</a> to turn missing evidence into a next-action list. Then follow the <a href="/guides/photo-recovery-drill/">non-destructive recovery drill</a>. Neither tool grants permission to erase the source. Keep originals until you understand the remaining risks and have verified the copies you need.</p>`]
 ]
},
{
 slug: 'verify-a-file-copy', category: '02 / Verify a copy', title: 'How to verify a copied photo file—and understand a mismatch',
 description: 'Use a local byte comparison, interpret SHA-256 fingerprints, and distinguish a failed copy from an edited or converted photo export.',
 minutes: 7, sources: ['digest','googleQuality','appleCopy'],
 sections: [
 ['start', 'A copy check answers one narrow question', `<p>Two files can show the same photograph without containing the same bytes. One might be a resized JPEG, the other an original HEIC. Conversely, two byte-identical copies can both contain a damaged original. Decide which question you want to answer before choosing a test.</p><p>The <a href="/tools/file-copy-check/">KYD file copy checker</a> answers: <strong>are these two selected files byte-for-byte identical?</strong> It reads them locally, compares every byte and displays a SHA-256 fingerprint for each. It does not upload, decode, repair or delete them. It does not scan a folder, inspect your cloud account or authenticate the person who created a file.</p>`],
 ['procedure', 'A small, repeatable comparison', `<ol><li>Keep the source untouched. Copy it to a different location using your normal file-copy method.</li><li>Wait for the copy operation to finish. Make sure both are actual downloaded files rather than cloud placeholders.</li><li>Select the source as File A and the copied file as File B in the checker. The tool accepts files up to 32 MiB each.</li><li>Run the comparison. Record the result and the two fingerprints locally if needed.</li><li>Open the copied image in a trusted viewer. For a video, also check playback and audio. A byte comparison is not a media-decoding test.</li></ol><p>The file picker only grants this page access to the files you choose. Cloud-backed file pickers may themselves download a file through the operating system before the browser can read it. That is different from this tool uploading anything. If you need to avoid that download, choose files already saved locally.</p>`],
 ['outcomes', 'Interpret the result without jumping to a conclusion', `<div class="table-wrap"><table><thead><tr><th>Result</th><th>What it establishes</th><th>Next step</th></tr></thead><tbody><tr><th>Byte-identical</th><td>The selected contents match at the time of reading. Names and timestamps are not compared.</td><td>Open the copy. Keep checking the rest of the collection and independence of storage.</td></tr><tr><th>Different byte sizes</th><td>These are not identical copies.</td><td>Check whether you selected an original versus an export, edit or thumbnail.</td></tr><tr><th>Same size, different bytes</th><td>Size alone would have missed the difference.</td><td>Compare export settings and repeat a plain copy into a new folder.</td></tr><tr><th>Unable to read / too large</th><td>No comparison was completed.</td><td>Leave the originals alone. Use an appropriate trusted desktop verification tool for larger files.</td></tr></tbody></table></div><p>Google Photos Storage saver can compress or change a file’s format. Apple also distinguishes exporting originals from other ways of saving photos. A mismatch after conversion is not, by itself, evidence of corruption. If your goal is to preserve the camera original, compare unmodified originals rather than a rendered edit. Keep a useful edited version as an additional item if you want both.</p>`],
 ['demo', 'Try a known result before selecting personal files', `<p>The checker has a built-in demonstration using three tiny text byte sequences, not photos. It compares <code>abc</code> with another <code>abc</code>, then with <code>abd</code>. The first pair must match. The second pair must differ even though both files are three bytes long.</p><p>The expected SHA-256 for the UTF-8 bytes of <code>abc</code>, with no newline, is:</p><pre class="fingerprint">ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad</pre><p>This fixture catches a particularly bad implementation: declaring two files equal because their names or sizes match. KYD’s direct comparison checks contents; the fingerprint is also useful as a record you can compare later. A fingerprint has no built-in proof of origin—an untrusted file accompanied by an untrusted fingerprint is still untrusted.</p>`],
 ['limits', 'Where this check stops', `<p>One match does not inventory a whole library, preserve album membership or confirm account recovery. Live or motion photos can involve more than a single still-image file; companion media and metadata need their own checks. Do not treat selecting one exported JPEG as a test of every component.</p><p>The browser digest API reads whole inputs into memory, so this implementation caps each file at 32 MiB. It deliberately avoids promising multi-gigabyte video verification. For a collection, maintain a manifest and use a suitable batch verification workflow; do not laboriously rename hundreds of originals to fit a two-file tool.</p><p>After a successful copy comparison, test the broader recovery path using the <a href="/guides/photo-recovery-drill/">recovery drill</a>. A copy that cannot be found, opened or accessed without a lost device is not yet a useful recovery plan.</p>`]
 ]
},
{
 slug: 'plan-photo-backup-space', category: '03 / Plan room to grow', title: 'Plan photo backup space from your own library—not a photo-count estimate',
 description: 'Calculate a new backup destination’s space budget with growth, retained versions and reserve. Includes reproducible examples and GB/GiB conversion.',
 minutes: 6, sources: ['appleCopy','googleQuality'],
 sections: [
 ['measure', 'Measure the files you intend to preserve', `<p>“Ten thousand photos” is not a capacity measurement. The space needed by ten thousand small screenshots is different from that of a mixed library containing RAW photographs and long videos. Start with the byte size of the files you actually plan to copy.</p><p>This planner budgets a <strong>new, full copy on one destination</strong>. It is not a subscription recommendation or a prediction of phone storage. If a destination already contains part of the same archive, do not blindly add the full library again: first establish what exists and what your backup software will retain. Do not delete that existing copy to make the estimate fit.</p><p>Use exported-file sizes where possible. Optimized phone storage or a compressed cloud collection may not represent the size of the originals you want to keep. Export a manageable sample, check its format, then measure the actual collection when feasible.</p>`],
 ['formula', 'Make the assumptions visible', `<div class="formula">Future archive = current archive + monthly growth × months + extra retained versions<br>Space budget = future archive ÷ (1 − reserve fraction)</div><p>Reserve is a chosen planning allowance, not a manufacturer requirement. In this model it is a fraction of the total allocated space budget. A 20% reserve therefore means dividing by 0.8, not simply adding 20% to the data amount.</p><p>“Extra retained versions” means additional old or changed files kept alongside the current archive. Enter zero if you are planning only one full version, but recognize that doing so does not budget version history. Software that retains multiple full snapshots could need much more space; this simple model does not simulate deduplication or compression.</p>`],
 ['example', 'Worked case: 120 GB today, a year of growth', `<p><strong>Hypothetical inputs, not a measured user library:</strong> 120 GB current archive, 4 GB of net additions per month, 12 months, 30 GB of extra retained versions, and a 20% reserve.</p><ol><li>Growth: 4 × 12 = <strong>48 GB</strong>.</li><li>Future archive plus versions: 120 + 48 + 30 = <strong>198 GB</strong>.</li><li>Total budget: 198 ÷ 0.8 = <strong>247.5 GB</strong>.</li><li>If the intended destination reports 200 GB of free space, the gap is <strong>47.5 GB</strong>.</li></ol><p>The answer is not “buy the next advertised size.” Compare with usable free space after formatting and other stored files. If you intend two independent destinations, each needs its own suitable budget; two copies competing for the same free space do not create two independent devices.</p><p>Run these numbers in the <a href="/tools/storage-planner/">backup space planner</a>. It also doubles only your growth assumption for a sensitivity check: 120 + 8 × 12 + 30 = 246 GB of data, requiring 307.5 GB with the same reserve. The 60 GB difference shows why a small change in monthly capture habits can matter more than rounding a current reading.</p>`],
 ['units', 'Keep GB and GiB separate', `<p>This tool uses decimal GB: 1 GB = 1,000,000,000 bytes. A GiB is 1,073,741,824 bytes. Consequently, 247.5 GB is about 230.5 GiB. These are two unit labels for the same number of bytes, not evidence that files disappeared.</p><p>If a file manager reports GiB, use the unit-conversion field before entering capacity numbers. If its label is ambiguous, prefer an exact byte count or the operating system’s documentation. Mixing a decimal budget with a binary free-space reading can produce a false shortage or surplus.</p>`],
 ['maintain', 'Replace the estimate with observations', `<p>Write down the collection size and the date at two comparable points. Net additions divided by elapsed months give a starting growth estimate. A month with an overseas trip or a video project may not represent the rest of the year; test a higher-growth scenario separately.</p><p>Revisit the plan after changing camera quality, adding RAW files, keeping edited copies or changing retention settings. A plan can be arithmetically correct and operationally wrong if those assumptions change. Space is only one part of a backup: finish by checking <a href="/guides/verify-a-file-copy/">copy integrity</a> and whether you can actually <a href="/guides/photo-recovery-drill/">retrieve the files</a>.</p>`]
 ]
},
{
 slug: 'photo-recovery-drill', category: '04 / Practice recovery', title: 'A non-destructive photo recovery drill you can repeat',
 description: 'Test whether a small sample can be retrieved, opened and understood without deleting originals. Includes an observation sheet and clear stop conditions.',
 minutes: 7, sources: ['appleCopy','googleBackup'],
 sections: [
 ['scope', 'Test retrieval, not your luck', `<p>A backup routine ends with an observation: the copied material can be retrieved and used. This drill is designed to produce that observation without wiping a device, emptying a trash folder or disconnecting an account. It is a planning method developed for this site, not a claim that KYD has tested your hardware or cloud subscription.</p><p>Set aside a short, uninterrupted session. Use a small sample first, retain the originals, and create a new destination folder that is not part of your photo synchronization. Do not change live retention settings to perform the exercise.</p>`],
 ['choose', 'Choose a sample that can reveal different failures', `<div class="table-wrap"><table><thead><tr><th>Sample</th><th>Reason to include it</th><th>Observation to record</th></tr></thead><tbody><tr><th>Recent photo</th><td>Exposes a stalled or incomplete recent upload.</td><td>Correct image, expected dimensions and usable export.</td></tr><tr><th>Older imported photo</th><td>Challenges the assumption that every folder was included.</td><td>Found by date or known context, not only by a thumbnail.</td></tr><tr><th>Video</th><td>Adds a playback and sound check.</td><td>Beginning, middle and end play; expected audio is present.</td></tr><tr><th>Special format you use</th><td>A still JPEG may omit motion, RAW data or an edited version.</td><td>The components and behavior you actually need survive the export.</td></tr></tbody></table></div><p>This is a targeted sample, not a statistical certificate. Add personally important material that would be costly or impossible to replace. Keep that list private; no one needs to know the contents for you to use the worksheet.</p>`],
 ['run', 'Run the drill without deleting the source', `<ol><li><strong>State the route.</strong> For example: “Retrieve an exported copy from the external drive into a new test folder.” Do not just write “backup works.”</li><li><strong>Retrieve.</strong> Copy the sample out of the backup location. Use the provider’s documented export route for cloud material. Note the account or device dependency privately without recording credentials.</li><li><strong>Open locally.</strong> After retrieval completes, open the downloaded files from the test folder, not from a link in the cloud app. If testing offline access, disconnect only after downloads finish and only if doing so will not interrupt other work.</li><li><strong>Inspect.</strong> Check content, dimensions, video playback and special-format components. For a plain, unmodified file copy within the 32 MiB limit, also use the <a href="/tools/file-copy-check/">local byte comparison</a>.</li><li><strong>Record and retain.</strong> Keep a short result, date and next action. Leave the originals and the backup unchanged.</li></ol><p>The export route matters. Apple documents separate ways to copy originals and notes limitations for Shared Albums. Google’s folder and item backup checks help identify what entered a cloud library. Neither substitutes for opening your own retrieved sample.</p>`],
 ['worksheet', 'Use a record that separates facts from assumptions', `<div class="worksheet"><h3>Recovery observation sheet</h3><p>Date: ____________________ &nbsp; Device / app version: ____________________</p><p>Retrieval route (no passwords): __________________________________________</p><p>Sample scope and formats: ______________________________________________</p><p>Observed result: ☐ Retrieved ☐ Opened ☐ Video checked ☐ Components checked</p><p>Still untested: ________________________________________________________</p><p>Next action and next check date: ________________________________________</p></div><p>Print this page or use your own private note. A filename can reveal a person, event or location; store the sheet where you would store other private backup records. Do not attach it unredacted to a public issue.</p><p><strong>Example record:</strong> “October 7: three synthetic test files copied into a separate folder; contents compared. No cloud export, photo decoding or full-library recovery tested.” This is the kind of limited statement a software test can support. It would be misleading to rewrite it as “all photos are safe.”</p>`],
 ['stop', 'Stop when a result is ambiguous', `<ul><li>A sample is missing: identify the missing folder or date range before any cleanup.</li><li>A file opens only online: establish whether you saved a placeholder, a link or the complete file.</li><li>A hash differs: check for conversion or editing; do not label the original corrupt from that result alone.</li><li>A copy needs the same unavailable account: your recovery dependency remains unresolved.</li><li>The drive disconnects, reports errors or is physically failing: stop repeated experiments and seek appropriate recovery help.</li></ul><p>Schedule your own next check after a major library move, export-setting change or new storage device. There is no universal interval that proves safety. The value comes from noticing when your assumptions no longer match the actual retrieval path.</p><p>Return to the <a href="/tools/photo-backup-check/">backup self-check</a> to identify unfinished checks, or to the <a href="/guides/before-deleting-photos/">copy map</a> if the independence of your copies is unclear.</p>`]
 ]
}
];
module.exports = {reviewed,sources,guides};
