'use strict';
// Source-based guidance; the three-item case is explicitly hypothetical.
module.exports = {
 slug: 'google-photos-takeout-json-dates', category: '05 / Preserve the context',
 title: 'Google Photos Takeout JSON files: what to keep before fixing dates',
 description: 'Keep photo context intact after a Google Photos export: distinguish file dates from capture dates, review JSON companions, and use a three-item audit worksheet.',
 published: '2026-10-08', reviewed: '2026-10-08', minutes: 8,
 sources: ['googleTakeout','locPhotoContext'],
 sections: [
 ['answer','Keep the JSON files while you check the export',`<p><strong>Do not discard the JSON files just because your photos open without them.</strong> A viewable picture and a well-described picture are different preservation goals. Before tidying a Google Photos Takeout export, keep an untouched copy of the downloaded archives, retain the extracted folder structure, and investigate a small working sample.</p><p>This guide addresses one specific problem: an export contains unfamiliar JSON files, and old photos appear under a recent date. The aim is to decide what needs investigation before renaming, importing or rewriting anything—not to promise a one-click metadata repair.</p><div class="notice"><strong>Your useful output:</strong> a short record for three items showing which date you actually inspected, where companion information lives, and what remains unresolved. The <a href="#worksheet">blank worksheet</a> is free to download; no account or upload is needed.</div>`],
 ['layers','Separate three kinds of information',`<p>Google’s <a href="https://support.google.com/accounts/answer/3024190?hl=en">download documentation</a> distinguishes a timestamp assigned by the operating system during download from original timestamps inside the media. It also says additional information, such as Google Photos comments, is exported into secondary JSON files. That is not a claim that every exported image has every field you expect.</p><div class="table-wrap"><table><caption>These are different evidence sources, not three values that must always agree.</caption><thead><tr><th>Layer</th><th>What you are looking at</th><th>Question to ask</th></tr></thead><tbody><tr><th>File-system date</th><td>A field such as file creation or modification time in your file manager.</td><td>Am I seeing a file operation date rather than the photograph’s capture date?</td></tr><tr><th>Embedded media metadata</th><td>Fields read from inside the image or video, if present.</td><td>Which exact field is this viewer showing, and does it actually describe capture?</td></tr><tr><th>Companion information</th><td>Separate JSON data associated with the export.</td><td>Does this contain context I need to preserve, and can I establish what it describes?</td></tr></tbody></table></div><p>A column simply called “Date” is too ambiguous for a repair decision. Record its full label and the application. An absent field means <em>not found in this inspection</em>; it does not prove the picture was taken on the download date. Likewise, an old date in a filename is a clue, not independent proof of capture time.</p>`],
 ['protect','Set up a working sample without flattening the archive',`<p>Google notes that a large export can arrive in several archives. Confirm that you have downloaded the parts listed for your export before treating a missing item as lost. Recent library changes may also fall outside an export’s contents. Record the export request and download dates so you know which snapshot you are reviewing.</p><ol><li><strong>Preserve the delivery.</strong> Keep the downloaded archive files unchanged. Do not rename or delete their contents as your first organizing step.</li><li><strong>Separate extraction from experiments.</strong> Extract into a fresh, clearly named location. If a file conflict or overwrite prompt appears, stop and investigate instead of choosing “replace all.”</li><li><strong>Copy a small working set.</strong> Choose an older camera photo, a screenshot or edited image, and a video. Keep their relative folders and candidate JSON files together. These cases can reveal different gaps.</li><li><strong>Write down what you copied.</strong> Record the original relative path and archive part. Do not merge everything into a single folder: repeated filenames would become harder to distinguish.</li></ol><pre class="fingerprint" aria-label="Suggested local working folders, not the format of a Google Takeout archive">My photo-export review/
  downloads-kept-unchanged/
  extracted-kept-unchanged/
  working-sample/
  review-notes.txt</pre><p>This is KYD’s suggested local arrangement, <strong>not a representation of Google’s archive structure</strong>. Three folders on one drive do not make three independent backups. Use the <a href="/guides/plan-photo-backup-space/">capacity guide</a> to allow for archives, extracted files and working copies, and keep a separate recovery copy where appropriate.</p>`],
 ['case','Worked example: one “wrong date,” three different decisions',`<p><strong>Invented observations for teaching—not a test of a real Google account:</strong> someone downloaded an export on October 8, 2026. Their file manager shows that day for all three sample files. They then inspect the media and candidate companion data without changing either.</p><div class="table-wrap"><table><caption>Fictional review record. Identifiers A, B and C are worksheet labels, not Takeout filenames or JSON field names.</caption><thead><tr><th>Sample</th><th>Additional observation</th><th>Decision</th></tr></thead><tbody><tr><th>A · Camera photo</th><td>The viewer’s capture-date field shows August 14, 2019. The picture opens correctly.</td><td>No evidence yet that its embedded capture date needs repair. Check the file manager’s sorting field first.</td></tr><tr><th>B · Screenshot</th><td>No capture-date field is exposed by this viewer. A candidate JSON file contains a date, but its association with B is uncertain.</td><td>Leave the date unresolved. Do not write a guessed timestamp into the image.</td></tr><tr><th>C · Video</th><td>Playback works. Companion information contains a description the owner wants, but the destination app does not display it in the sample import.</td><td>Keep that companion data and record the import limitation. Playback alone did not preserve all desired context.</td></tr></tbody></table></div><p>The three files look identical under one file-manager date column, but they call for three different actions. A bulk command that assigns that column’s date to every media file would erase the distinction the review just uncovered.</p><p>In this example, one item needs no demonstrated capture-date repair, one remains unresolved, and one needs a context-preservation decision. None of those outcomes authorizes deleting the source library.</p>`],
 ['inspect','Inspect one item without rewriting it',`<ol><li><strong>Open the media itself.</strong> Use a trusted local viewer and its information panel. Note the complete field label, value and application version. If the viewer exposes no suitable field, record “not shown” instead of inventing a date.</li><li><strong>Inspect candidate JSON as text.</strong> Use a local plain-text viewer without saving changes. Do not upload family photos or metadata to an unknown online “fixer.” Names, descriptions and location-related fields may be private.</li><li><strong>Establish the association.</strong> Keep the original path, compare identifying information that is actually present, and consult documentation for the specific export or importer. A similar basename alone is not enough when several files share it. Do not assume every JSON file describes one photo.</li><li><strong>Test the destination with copies.</strong> If you intend to use a photo organizer, import only the sample into a separate test library where possible. Compare the displayed dates and wanted descriptions. Ask whether the importer supports this companion format; the presence of a JSON file does not establish support.</li><li><strong>Write a bounded conclusion.</strong> For example: “Photo opens; capture date displayed; description not imported; original export retained.” This is more useful than “metadata fixed.”</li></ol><p>If two displays disagree, preserve both values and their labels. A different timezone display is one possibility, not an automatic diagnosis. Do not apply a library-wide time offset until you know what each field and application represents.</p>`],
 ['decisions','When a cleanup or repair should stop',`<ul><li><strong>Several possible companions:</strong> preserve them and mark the association unresolved. A rename based on a guess can make a later match harder.</li><li><strong>Unreadable archive or extraction error:</strong> resolve that problem before reviewing metadata. A partial extraction is not a trustworthy inventory.</li><li><strong>An importer skips context:</strong> keep the original media and companion data even if you create a convenient browsing copy elsewhere.</li><li><strong>A proposed repair overwrites originals:</strong> do not run it on your only export. First understand which fields it writes and test reversible copies.</li></ul><p>The <a href="https://blogs.loc.gov/thesignal/2011/09/remember-when-we-had-photographs/">Library of Congress’s personal-archiving guidance</a> emphasizes keeping descriptions with photographs. The practical point here is not to preserve a particular file extension for its own sake: preserve the information you would otherwise lose about the image.</p><p>A metadata edit may change a file’s bytes even if its visible picture does not change. Use our <a href="/tools/file-copy-check/">local file copy checker</a> on an untouched source and a plain copy when the question is copy integrity; its limit is 32 MiB per file. It does not interpret JSON, determine a correct date, or verify an importer. See <a href="/guides/verify-a-file-copy/">how to interpret a mismatch</a> before labelling an edited derivative corrupt.</p>`],
 ['worksheet','Keep a review record you can use later',`<div class="worksheet"><h3>Three-item export review</h3><p>Export request / download dates: ____________________</p><p>Archive parts listed / downloaded: ____________________</p><p>Untouched copy location: ____________________</p><p>For each sample: relative path · media opens? · date field label and value · candidate companion path · association confirmed or unresolved · wanted context · sample import result · next action.</p><p>Remaining unknowns: ____________________</p></div><p><a class="button secondary" href="/assets/worksheets/takeout-review.txt" download="kyd-takeout-review.txt">Download the blank text worksheet</a></p><p>The worksheet is an original KYD template, not a Google export parser or a certificate. You may save, adapt and print it for your own archive. Fill it out locally; this website does not receive your notes. Keep completed records private and never include passwords or recovery codes.</p><p><strong>Done for this session means:</strong> the delivered archives are retained, each inspected field is identified, ambiguous associations stay unresolved, and the next action is written down. Before relying on the export as a recovery copy, continue with the <a href="/guides/photo-recovery-drill/">non-destructive recovery drill</a>. Do not delete originals merely because three samples passed.</p>`]
 ]
};
